name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go version

      - run: go build .
      - name: test
        run: go test -json > TestResults.json
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults.json
      - name: Upload binary
          uses: actions/upload-artifact@v3
          with:
            name: linux-binary
            path: workflow-jwt-creator

      - name: Upload test results
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: TestResults.json
